FROM rust:1.77-bookworm

ENV DEBIAN_FRONTEND=noninteractive

# Tooling needed for building PyOxidizer-based `ppt` binaries.
RUN apt-get update -qq && apt-get install -y -qq \
    bash \
    build-essential \
    ca-certificates \
    curl \
    gzip \
    make \
    musl-tools \
    python3 \
    tar \
  >/dev/null

# Build tool. (Pinned for reproducibility.)
RUN cargo install pyoxidizer --locked --version 0.24.0
